# 异常处理

程序异常可分为逻辑异常和语法异常，对于初学者而言语法异常居多，随着不断的学习对语言越来越熟悉后语法异常减少逻辑异常增多。

在JavaScript中提供了对异常进行处理的语句，在适当的时候使用它们能够使程序变得更加健壮。

但是要注意不要滥用异常处理，它会使程序的可读性变差。



# 异常类型

所有的异常都是对象，在JavaScript中，常见异常类型有以下几种：

| 异常类型       | 简述                                                         |
| -------------- | ------------------------------------------------------------ |
| Error          | 基本异常，该异常作为所有异常的基类产生                       |
| EvalError      | eval错误，一般是由于不当的使用eval()函数产生                 |
| RangeError     | 范围错误，常见于Array中产生，如索引无效                      |
| ReferenceError | 引用错误，常见于定义变量时产生，如变量名不存在               |
| SyntaxError    | 语法错误                                                     |
| TypeError      | 类型错误                                                     |
| URIError       | 在使用encodeURI()或者decodeURI()因为URL格式不正确时，就会导致URIError错误。 |



# 异常捕获

## try catch

使用try与catch语句进行捕获异常：

- try用于检测可能出现异常的代码块
- catch用于处理捕捉到的异常，可指定参数获取异常信息

try/catch语句有一个包含一条或者多条语句的，0个或1个的catch代码块，catch代码块中的语句会在try代码块中抛出异常时执行。

如果try代码块中的语句（或者try代码块中调用的方法）一旦抛出了异常，那么执行流程会立即进入catch代码块。

如果try代码块没有抛出异常，catch代码块就会被跳过：

```
"use strict";

try {
    console.log(username);
} catch (e) {
    console.log("处理了一个异常:", e);
}

// 处理了一个异常,ID: ReferenceError: username is not defined
```



## finally

finally块包含了在try和catch块完成后、下面接着try/catch的语句之前执行的语句。

finally块无论是否抛出异常都会执行，如果抛出了一个异常，就算没有异常处理，finally块里的语句也会执行：

```
"use strict";

try {
    console.log(username);
} catch (e) {
    console.log("处理了一个异常,ID:", e);
} finally {
    console.log("无论有没有异常都会执行我");
}


// 处理了一个异常,ID: ReferenceError: username is not defined
// 无论有没有异常都会执行我
```



# 主动异常

## throw new Error

在某些时候我们需要主动抛出异常，使用throw语句抛出异常：

```
"use strict";

throw new Error("这是一个错误")

// demo.js:3 Uncaught Error: 这是一个错误
```



## 表达式形式

你可以抛出任意表达式而不是特定一种类型的表达式。

下面的代码中抛出了几个不同类型的表达式：

```
"use strict";

throw "Error2";   // String type
throw 42;         // Number type
throw true;       // Boolean type
throw { toString: function () { return "I'm an object!"; } };
```



# 自定义异常

## 原型继承

继承Error原型对象，可配置自定义的异常。

Error构造函数具有message可选参数，用于显示人类可阅读的错误描述信息。

如下所示：

```
"use strict";

function MyError(message) {
    this.name = 'MyError';
    this.message = message || 'Default Message';
    this.stack = (new Error()).stack;
}

Object.setPrototypeOf(MyError, Error);  // 继承Error原型对象

try {
    throw new MyError();
} catch (e) {
    console.log(e.name);  // MyError
    console.log(e.message);  // Default Message
}


try {
    throw new MyError("自定义异常被抛出");
} catch (e) {
    console.log(e.name);  // MyError
    console.log(e.message);  // 自定义异常被抛出
}

// MyError
// Default Message
// MyError
// 自定义异常被抛出
```



## 类继承

使用class语法进行自定义异常：

```
"use strict";

class MyError extends Error {
    constructor(message) {
        super();
        this.name = "MyError";
        this.message = message || 'Default Message';
        this.stack = (new Error()).stack;
    }
}

try {
    throw new MyError();
} catch (e) {
    console.log(e.name);
    console.log(e.message);
}


try {
    throw new MyError("自定义异常被抛出");
} catch (e) {
    console.log(e.name);
    console.log(e.message);
}

// MyError
// Default Message
// MyError
// 自定义异常被抛出
```

